ci:
  autoupdate_commit_msg: "chore: [pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: |
          (?x)(
              ^assets/.*|
              \.svg|
              \.scss|
              \.map|
              \.min.js
          )$
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        types_or: [yaml, css, scss, javascript, json]
        exclude: |
          (?x)(
              ^assets/js/.*|
              ^assets/fonts/.*|
              ^assets/css/.*|
              \.min.js|
              \.min.css
          )$

  - repo: local
    hooks:
      - id: data-filenames
        files: ^_data/.*(?<!\.yml)$
        name: Force _data files to be .yml
        entry: files in _data must end in .yml
        language: fail

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        exclude: |
          (?x)^(
              Gemfile.lock|
              assets/.*|
              \.js|
              \.map|
              \.css
          )$
        args: ["-L", "hist,slac,rouge,nd"]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.1
    hooks:
      - id: check-github-workflows
        args: ["--verbose"]
